import type { Movement } from '../types';

/**
 * SPEC 10.2/10.6: common studio-lifting movements not already covered by
 * `seed/movements.json`, seeded into the `vasa` library on migration to
 * schemaVersion 3 (`migrate.ts`) and on first run (`storage/seed.ts`).
 * `region` is set explicitly on every entry rather than left to
 * `vasa/region.ts`'s tag-based derivation, since a few of these (e.g. a
 * single-arm upper-body press) carry the `unilateral` tag for accuracy but
 * would otherwise derive to 'full' by matching both the lower- and
 * upper-body tag sets.
 */
export const VASA_SEED_MOVEMENTS: Movement[] = [
  {
    id: 'hip_thrust',
    name: 'Hip Thrust',
    tags: ['compound', 'hinge', 'legs'],
    equipment: ['barbell', 'bench'],
    cadenceDays: 7,
    unit: 'reps',
    loadable: true,
    libraries: ['vasa'],
    region: 'lower',
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    tags: ['unilateral', 'squat', 'legs', 'accessory'],
    equipment: ['dumbbell', 'bench'],
    cadenceDays: 3,
    unit: 'reps',
    loadable: true,
    libraries: ['vasa'],
    region: 'lower',
  },
  {
    id: 'reverse_lunge',
    name: 'Reverse Lunge',
    tags: ['unilateral', 'legs', 'accessory'],
    equipment: ['dumbbell'],
    cadenceDays: 3,
    unit: 'reps',
    loadable: true,
    libraries: ['vasa'],
    region: 'lower',
  },
  {
    id: 'dumbbell_bench_press',
    name: 'Dumbbell Bench Press',
    tags: ['compound', 'push'],
    equipment: ['dumbbell', 'bench'],
    cadenceDays: 3,
    unit: 'reps',
    loadable: true,
    libraries: ['vasa'],
    region: 'upper',
  },
  {
    id: 'incline_dumbbell_press',
    name: 'Incline Dumbbell Press',
    tags: ['push', 'accessory'],
    equipment: ['dumbbell', 'bench'],
    cadenceDays: 3,
    unit: 'reps',
    loadable: true,
    libraries: ['vasa'],
    region: 'upper',
  },
  {
    id: 'incline_dumbbell_fly',
    name: 'Incline Dumbbell Fly',
    tags: ['push', 'accessory'],
    equipment: ['dumbbell', 'bench'],
    cadenceDays: 3,
    unit: 'reps',
    loadable: true,
    libraries: ['vasa'],
    region: 'upper',
  },
  {
    id: 'landmine_press',
    name: 'Landmine Press',
    tags: ['push', 'unilateral', 'accessory'],
    equipment: ['barbell', 'landmine'],
    cadenceDays: 3,
    unit: 'reps',
    loadable: true,
    libraries: ['vasa'],
    region: 'upper',
  },
  {
    id: 'lateral_raise',
    name: 'Lateral Raise',
    tags: ['push', 'accessory'],
    equipment: ['dumbbell'],
    cadenceDays: 3,
    unit: 'reps',
    loadable: true,
    libraries: ['vasa'],
    region: 'upper',
  },
  {
    id: 'band_pull_apart',
    name: 'Band Pull-apart',
    tags: ['pull', 'accessory'],
    equipment: ['band'],
    cadenceDays: 3,
    unit: 'reps',
    loadable: false,
    libraries: ['vasa'],
    region: 'upper',
  },
  {
    id: 'face_pull_band',
    name: 'Face Pull (band)',
    aliases: ['face pull'],
    tags: ['pull', 'accessory'],
    equipment: ['band'],
    cadenceDays: 3,
    unit: 'reps',
    loadable: false,
    libraries: ['vasa'],
    region: 'upper',
  },
  {
    id: 'band_tricep_extension',
    name: 'Band Tricep Extension',
    tags: ['push', 'accessory'],
    equipment: ['band'],
    cadenceDays: 3,
    unit: 'reps',
    loadable: false,
    libraries: ['vasa'],
    region: 'upper',
  },
  {
    id: 'band_bicep_curl',
    name: 'Band Bicep Curl',
    tags: ['pull', 'accessory'],
    equipment: ['band'],
    cadenceDays: 3,
    unit: 'reps',
    loadable: false,
    libraries: ['vasa'],
    region: 'upper',
  },
  {
    id: 'dumbbell_curl',
    name: 'Dumbbell Curl',
    tags: ['pull', 'accessory'],
    equipment: ['dumbbell'],
    cadenceDays: 3,
    unit: 'reps',
    loadable: true,
    libraries: ['vasa'],
    region: 'upper',
  },
  {
    id: 'tricep_kickback',
    name: 'Tricep Kickback',
    tags: ['push', 'accessory'],
    equipment: ['dumbbell'],
    cadenceDays: 3,
    unit: 'reps',
    loadable: true,
    libraries: ['vasa'],
    region: 'upper',
  },
  {
    id: 'chest_supported_row',
    name: 'Chest-supported Row',
    tags: ['pull', 'accessory'],
    equipment: ['dumbbell', 'bench'],
    cadenceDays: 3,
    unit: 'reps',
    loadable: true,
    libraries: ['vasa'],
    region: 'upper',
  },
  {
    id: 'single_arm_kettlebell_row',
    name: 'Single-arm Kettlebell Row',
    tags: ['pull', 'unilateral', 'accessory'],
    equipment: ['kettlebell', 'bench'],
    cadenceDays: 3,
    unit: 'reps',
    loadable: true,
    libraries: ['vasa'],
    region: 'upper',
  },
  {
    id: 'kettlebell_deadlift',
    name: 'Kettlebell Deadlift',
    tags: ['compound', 'hinge', 'legs'],
    equipment: ['kettlebell'],
    cadenceDays: 7,
    unit: 'reps',
    loadable: true,
    libraries: ['vasa'],
    region: 'lower',
  },
  {
    id: 'goblet_reverse_lunge',
    name: 'Goblet Reverse Lunge',
    tags: ['unilateral', 'legs', 'accessory'],
    equipment: ['kettlebell'],
    cadenceDays: 3,
    unit: 'reps',
    loadable: true,
    libraries: ['vasa'],
    region: 'lower',
  },
  {
    id: 'nordic_curl',
    name: 'Nordic Curl',
    tags: ['hinge', 'legs', 'accessory', 'bodyweight'],
    equipment: ['none'],
    cadenceDays: 3,
    unit: 'reps',
    loadable: false,
    libraries: ['vasa'],
    region: 'lower',
  },
  {
    id: 'glute_bridge',
    name: 'Glute Bridge',
    tags: ['hinge', 'legs', 'accessory', 'bodyweight'],
    equipment: ['none'],
    cadenceDays: 3,
    unit: 'reps',
    loadable: false,
    libraries: ['vasa'],
    region: 'lower',
  },
  {
    id: 'hollow_hold',
    name: 'Hollow Hold',
    tags: ['core', 'bodyweight'],
    equipment: ['none'],
    cadenceDays: 3,
    unit: 'seconds',
    loadable: false,
    libraries: ['vasa'],
    region: 'full',
  },
  {
    id: 'bird_dog',
    name: 'Bird Dog',
    tags: ['core', 'unilateral', 'bodyweight'],
    equipment: ['none'],
    cadenceDays: 3,
    unit: 'reps',
    loadable: false,
    libraries: ['vasa'],
    region: 'full',
  },
  {
    id: 'pallof_press_band',
    name: 'Pallof Press (band)',
    aliases: ['pallof press'],
    tags: ['core', 'accessory'],
    equipment: ['band'],
    cadenceDays: 3,
    unit: 'reps',
    loadable: false,
    libraries: ['vasa'],
    region: 'full',
  },
  {
    id: 'copenhagen_plank',
    name: 'Copenhagen Plank',
    tags: ['core', 'unilateral', 'bodyweight'],
    equipment: ['bench'],
    cadenceDays: 3,
    unit: 'seconds',
    loadable: false,
    libraries: ['vasa'],
    region: 'full',
  },
  {
    id: 'box_step_over',
    name: 'Box Step-over',
    tags: ['unilateral', 'legs', 'accessory'],
    equipment: ['box'],
    cadenceDays: 3,
    unit: 'reps',
    loadable: false,
    libraries: ['vasa'],
    region: 'lower',
  },
  {
    id: 'kettlebell_halo',
    name: 'Kettlebell Halo',
    tags: ['core', 'accessory'],
    equipment: ['kettlebell'],
    cadenceDays: 3,
    unit: 'reps',
    loadable: true,
    libraries: ['vasa'],
    region: 'full',
  },
  {
    id: 'suitcase_carry',
    name: 'Suitcase Carry',
    aliases: ['suitcase carry (dumbbell/kettlebell)'],
    tags: ['core', 'unilateral', 'carry'],
    equipment: ['dumbbell'],
    cadenceDays: 3,
    unit: 'seconds',
    loadable: true,
    libraries: ['vasa'],
    region: 'full',
  },
];
