name: Local Testing (Act-Optimized)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4.2.2
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2.21.0
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
    
    - name: Disable Flutter analytics
      run: flutter config --no-analytics
    
    - name: Clean and get dependencies
      run: |
        flutter clean
        flutter pub get --verbose
      continue-on-error: false
    
    - name: Verify formatting
      run: dart format --output=none --set-exit-if-changed .
      continue-on-error: true
    
    - name: Analyze project source
      run: flutter analyze
      continue-on-error: true
    
    - name: Check for test directories
      run: |
        echo "Checking test directories..."
        ls -la test/ || echo "No test directory found"
        find . -name "*.dart" -path "*/test/*" | head -10 || echo "No test files found"
    
    - name: Run basic flutter test
      run: flutter test
      continue-on-error: true
    
    - name: Build APK (debug)
      run: flutter build apk --debug
      continue-on-error: true
    
    - name: Summary
      run: |
        echo "=== Workflow Summary ==="
        echo "✅ Flutter SDK setup completed"
        echo "✅ Dependencies installed"
        echo "✅ Basic checks completed"
        echo "=== End Summary ==="